name: Build Kivy APK

on:
  push:
    branches:
      - main  # This runs the workflow every time you push to the "main" branch
  workflow_dispatch:  # Allows manual trigger of the workflow
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev libssl-dev
          sudo apt install -y build-essential libsqlite3-dev sqlite3
          sudo apt install -y libgstreamer1.0 libgstreamer-plugins-base1.0 gstreamer1.0-tools
          sudo apt install -y zlib1g-dev git curl
          pip install --upgrade pip
          pip install buildozer cython

      # Initialize Buildozer (optional, if no buildozer.spec file is present)
      # Uncomment the next line if you need to generate buildozer.spec
      # - name: Initialize Buildozer
      #   run: buildozer init

      # Build the APK
      - name: Build APK
        run: |
          buildozer android debug
        
      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./bin/*.apk
